FROM python:3.12

WORKDIR /code

COPY ./docker/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/code

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
