services:
  python-api:
    container_name: python-api
    build: 
      dockerfile: ./docker/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    

    
