name: Enforce Merge Policy

on:
  pull_request:
    branches:
      - prid

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch
        run: |
          if [[ "${{ github.head_ref }}" != "main" ]]; then
            echo "Only main can be merged into prod."
            exit 1
          fi