name: Create manual relese

on:
  workflow_dispatch: 
    inputs:
      tag:
        description: "Tag to deploy"
        required: true
        type: string

permissions:
  contents: write

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ inputs.tag }}
            name: Release ${{ inputs.tag }}
            body: "Release"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}