name: CI
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruff
        run: |
          curl -LsSf https://astral.sh/ruff/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run Ruff
        run: ruff check --output-format=github .
